In [10]:
#!/bin/python3

import numpy as np
import math
import os
import random
import re
import sys

#Diagonal Difference
#https://www.hackerrank.com/challenges/diagonal-difference/problem

a = np.array([[1,2,2],[4,1,6],[2,8,1]])
print(a)
i=0

#print(a)

diag1 = 0
diag2 = 0
j=0
#print(a[-1][-1])

for i in range(len(a)):
    diag1 += a[i][i]
    diag2 += a[i][-1-j]
    j+=1
        
print('first diagnal sum is: ', diag1)
print('second diagnal sum is: ', diag2)
print('absolute value of the two diagaols is:', abs(diag1-diag2))

[[1 2 2]
 [4 1 6]
 [2 8 1]]
first diagnal sum is:  3
second diagnal sum is:  5
absolute value of the two diagaols is: 2


In [82]:
#!/bin/python3

import math
import os
import random
import re
import sys

#Plus Minus
#https://www.hackerrank.com/challenges/plus-minus/problem

# Complete the plusMinus function below.
def plusMinus(arr):
    #arraySize = input()
    pos = neg = zer = 0
    for i in arr:
        if i == 0:
            zer += 1
        if i >= 1:
            pos += 1
        if i <= -1:
            neg += 1
            
    print("{0:.6f}".format(pos/len(arr)))
    print('%.6f'%(neg/len(arr)))
    print('%.6f'%(zer/len(arr)))

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)


5
5 5 0 -1 -1
0.400000
0.400000
0.200000


In [47]:
#!/bin/python3

#Staircase
#https://www.hackerrank.com/challenges/staircase/problem

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    
    space = ' '
    hashtag = '#'
    output = ''
    
    spaceCount, hashCount = n, 0
    
    for i in range(n):
        print(i)
        spaceCount -= 1
        hashCount += 1
        #print(spaceCount*(space)+hashCount*(hashtag))
        if(i!=n-1):
            output += (spaceCount*(space)+hashCount*(hashtag))+'\n'
        if(i==n-1):
            output += (spaceCount*(space)+hashCount*(hashtag))
    
    print(output)

if __name__ == '__main__':
    n = int(input())

    staircase(n)


5
0
1
2
3
4
    #
   ##
  ###
 ####
#####


In [12]:
#!/bin/python3

#Mini-Max Sum
#https://www.hackerrank.com/challenges/mini-max-sum/problem

import math
import os
import random
import re
import sys
import copy

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    
    #print(min(arr))
    #print(max(arr))
    #arr1 = copy.deepcopy(arr)
    #a = arr1.remove(max(arr))
    #arr.remove(min(arr))
    #print(sum(arr1), sum(arr))
    
    arrayForMin = copy.deepcopy(arr)
    arrayForMax = copy.deepcopy(arr)
    arrayForMin.remove(max(arrayForMin))
    arrayForMax.remove(min(arrayForMax))
    print(sum(arrayForMin), sum(arrayForMax))
    
if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)


1 2 3 4 5
10 14


In [24]:
#!/bin/python3

#Birthday Cake Candles
#https://www.hackerrank.com/challenges/birthday-cake-candles/problem

import math
import os
import random
import re
import sys
import numpy as np

# Complete the birthdayCakeCandles function below.
def birthdayCakeCandles(ar):
    
    tallestCandle = max(ar)
    occur = np.count_nonzero(ar==tallestCandle)
    
    print(occur)

if __name__ == '__main__':

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(ar)


5
1 2 3 4 5
0


In [39]:
#Birthday Cake Candles
#https://www.hackerrank.com/challenges/birthday-cake-candles/problem

list_num = [1, 2, 3, 4, 4]

maxval = max(list_num)
print(maxval)

occur = list_num.count(maxval)

print(occur)

#tup_num = (1, 2, 3)

#dir(list_num)
#dir(tup_num)

4
2


In [153]:
#!/bin/python3

#Time Conversion
#https://www.hackerrank.com/challenges/time-conversion/problem

import os
import sys
import string

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    #
    # Write your code here.
    #
    AMorPM = s[-2:]
    hr = s[:2]
    newTime = ''
    if(hr=='12' and AMorPM=='AM'):
        newTime = str('00')+s[2:-2]
    elif(hr=='12' and AMorPM=='PM'):
        newTime = s[:-2]
    elif(hr!='12' and AMorPM=='PM'):
        newTime = str(int(hr)+12)+s[2:-2]
    else:
        newTime = s[:-2]

    print(newTime)
    return newTime

if __name__ == '__main__':

    s = input()

    result = timeConversion(s)



12:00:00AM
00:00:00


In [231]:
a = [1, 2, 3]
b = [3, 2, 1]

lenA = len(a)
lenB = len(b)

same = False

if lenA == lenB:
    same = True
    pass

aScore = 0
bScore = 0

if same:
    for i in range(lenA):
        if a[i] > b[i]:
            aScore+=1
        elif a[i] < b[i]:
            bScore+=1
        else:
            pass

output = [aScore, bScore]
print(output)

True
<class 'list'>
[1, 1]
